[build]
builder = "BUILDPACK"
buildpack = "https://github.com/heroku/heroku-buildpack-php.git"

[deploy]
startCommand = "composer start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["php81"] 